<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="UK Data Service">

<title>Getting familiar with the Family Resources Survey using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="FRS_get_familiar_files/libs/clipboard/clipboard.min.js"></script>
<script src="FRS_get_familiar_files/libs/quarto-html/quarto.js"></script>
<script src="FRS_get_familiar_files/libs/quarto-html/popper.min.js"></script>
<script src="FRS_get_familiar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FRS_get_familiar_files/libs/quarto-html/anchor.min.js"></script>
<link href="FRS_get_familiar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FRS_get_familiar_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FRS_get_familiar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FRS_get_familiar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FRS_get_familiar_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #742082;
      }

      .quarto-title-block .quarto-title-banner {
        color: #742082;
background: white;
      }
</style>


<link rel="stylesheet" href="frs.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Getting familiar with the Family Resources Survey using R</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>UK Data Service </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a>
  <ul class="collapse">
  <li><a href="#setting-up-r" id="toc-setting-up-r" class="nav-link" data-scroll-target="#setting-up-r">Setting up R</a></li>
  </ul></li>
  <li><a href="#explore-the-data-sets" id="toc-explore-the-data-sets" class="nav-link" data-scroll-target="#explore-the-data-sets">Explore the data sets</a></li>
  <li><a href="#merging-data-sets" id="toc-merging-data-sets" class="nav-link" data-scroll-target="#merging-data-sets">Merging data sets</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing values</a></li>
  <li><a href="#compare-unweighted-and-weighted-proportions" id="toc-compare-unweighted-and-weighted-proportions" class="nav-link" data-scroll-target="#compare-unweighted-and-weighted-proportions">Compare unweighted and weighted proportions</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><strong>Confidence intervals</strong></a></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>This exercise is part of the ‘Getting started with <!-- add module name -->’ online module.</p>
<p>In the exercise, we examine data from the Family Resources Survey 2021/2022 financial year and explore:</p>
<ul>
<li><p>Two of the four well-being variables available in the data: <code>HAPPYWB</code> and <code>ANXIOUS</code>. The other two variables available are LIFESAT and MEANING.</p></li>
<li><p>How do these two variables vary across age groups, and</p></li>
<li><p>How do these two variables vary across family type.</p></li>
</ul>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<p>Data can be accessed from the <a href="http://doi.org/10.5255/UKDA-SN-9073-1">UK Data Service website</a> following registration.</p>
<p>To follow along with the exercise you will need to download the SPSS data format from the UK Data Service website. After saving the file on your machine, unzip everything and make sure the folder “UKDA-9073-spss” is placed in the folder which contains the R project FRS.Rproj and R script files FRS_get_familiar.qmd that you have obtained from the Github repository <!-- Add link to repository? --></p>
<p>The FRS is a big survey, as a result, the data is organised in multiple files. However, in this exercise, we will be using only two or three of these data files.</p>
<p>Using an R project (.Rproj) offers a structured, isolated, and reproducible working environment.</p>
<section id="setting-up-r" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-r">Setting up R</h3>
<p>To begin with, we need to load all R packages we will be using for this exercise. When using R and writing R scripts, it is good practice to have all the packages needed for analysis at the beginning of an R script.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co"># Data manipulation functions</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven) <span class="co"># Importing Stata/SPSS files</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="co"># Extra statistical functions</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#Data manipulation and visualization.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor) <span class="co">#Data cleaning and summary table</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co">#Tables in Quarto</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools) <span class="co">#Weighting</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Load the data files we are using in this exercise</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>frs_adult2122 <span class="ot">&lt;-</span> <span class="fu">read_spss</span> (<span class="st">"UKDA-9073-spss/spss/spss25/adult.sav"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>frs_benunit2122 <span class="ot">&lt;-</span> <span class="fu">read_spss</span> (<span class="st">"UKDA-9073-spss/spss/spss25/benunit.sav"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="explore-the-data-sets" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-data-sets">Explore the data sets</h2>
<p>To begin with, we will be focusing on exploring the “adult.sav” and “benunit.sav” datasets. The “adult.sav” file contains 590 variables while the “benunit.sav” file has 275 variables. We will only be using a few of these variables. As a result, it is better for us to create two subsets of the data, containing only the variables we are interested in.</p>
<p><strong>NOTE:</strong> These two files have different units of analysis. The “adult.sav” file contains data at the individual level while the “benunit.sav” file has data at the benefit unit level (see the <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9073#!/documentation">FRS documentation</a> for the definition of a benefit unit)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#use a pipeline (the %&gt;% operator) </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#and the "select" function from the dplyr package</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#the code below only selects the variables we are interested in</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>frs_adult2122_short <span class="ot">&lt;-</span> frs_adult2122 <span class="sc">%&gt;%</span> <span class="fu">select</span> (SERNUM, BENUNIT, PERSON, GROSS4, HAPPYWB, ANXIOUS, SEX, IAGEGR4)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>frs_benunit2122_short <span class="ot">&lt;-</span> frs_benunit2122 <span class="sc">%&gt;%</span> <span class="fu">select</span> (SERNUM, BENUNIT, FAMTYPBU)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Start by getting an overall feel of the two data sets.</p>
<p>We will start with the “adult” dataset. Either inspect variables and cases in the data editor or use the code below to produce a summary of all the variables in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(frs_adult2122_short) <span class="co">#Gives the number of rows (observations) and columns (variables)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27508     8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(frs_adult2122_short) <span class="co">#List variable names in their actual order in the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "SERNUM"  "BENUNIT" "PERSON"  "GROSS4"  "HAPPYWB" "ANXIOUS" "SEX"    
[8] "IAGEGR4"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(frs_adult2122_short)) <span class="co">#Displays the first few rows of a data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  SERNUM BENUNIT PERSON GROSS4 HAPPYWB ANXIOUS SEX IAGEGR4
1      1       1      1   1419       7       2   1      15
2      1       1      2   1419       7       7   2      14
3      2       1      1    177       7       0   2      12
4      2       1      2    177       9       0   1      12
5      3       1      1   8962       7       2   2       6
6      3       1      2   8962      NA      NA   1       6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#you can use tail(data.frame(frs_adult2122_short)) to display the last few rows of a data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s also have a quick look at the “benunit” dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(frs_benunit2122_short) <span class="co">#Gives the number of rows (observations) and columns (variables)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18541     3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(frs_benunit2122_short) <span class="co">#List variable names in their actual order in the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "SERNUM"   "BENUNIT"  "FAMTYPBU"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(frs_benunit2122_short)) <span class="co">#Displays the first few lines of a data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  SERNUM BENUNIT FAMTYPBU
1      1       1        1
2      2       1        4
3      3       1        4
4      4       1        6
5      5       1        3
6      6       1        5</code></pre>
</div>
</div>
<p><strong>Questions</strong></p>
<ol type="1">
<li><p>What is the overall sample size of each of the data sets?</p></li>
<li><p>How many variables are there in the short adult dataset?</p></li>
</ol>
<p>Now, let’s learn more about the available variables.</p>
<p><strong>Note</strong>: In traditional statistical software packages like SPSS or Stata, categorical variables are often represented as numeric codes with attached labels that convey their substantive meaning. R on the other hand allows for the use of alphanumeric variables or a specialised type of categorical variable known as ‘factors’. Factors in R can be ordered or unordered and are a fundamental aspect of R’s categorical data handling.</p>
<p>The <em>Haven</em> R package, which we use in this course, facilitates the conversion of categorical data from SPSS or Stata to R. While it can preserve the original numeric values it also contains attributes, which are special types of R objects with a name, accessible via the <em>attr()</em> function. In this context, each variable has two key attributes: a ‘label’, which is a description of the variable, and ‘labels’, which are the value labels.</p>
<p>Furthermore, the <em>Haven</em> R package allows for the conversion of these imported numeric variables into R factors. In this conversion, the factors are created with levels (i.e., categories) reflecting the value labels from SPSS or Stata. This approach offers a streamlined method to handle and analyse categorical data in R, bridging the gap between different statistical software methodologies.</p>
<p>Let’s examine the original variables’ description and value labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#the cat and names functions are only used in this case to make the output look better, but you do not need to use them</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>HAPPYWB,<span class="st">"label"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>How happy did you feel yesterday?</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>HAPPYWB,<span class="st">"labels"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Not at all happy" "1"                "2"                "3"               
 [5] "4"                "5"                "6"                "7"               
 [9] "8"                "9"                "Completely happy"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>ANXIOUS,<span class="st">"label"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>How anxious did you feel yesterday?</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>ANXIOUS,<span class="st">"labels"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Not at all anxious" "1"                  "2"                 
 [4] "3"                  "4"                  "5"                 
 [7] "6"                  "7"                  "8"                 
[10] "9"                  "Completely anxious"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>IAGEGR4,<span class="st">"label"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Individual Adult 5 Year Age Bands - Anon.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">attr</span>(frs_adult2122_short<span class="sc">$</span>IAGEGR4,<span class="st">"labels"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Age 16 to 19"   "Age 20 to 24"   "Age 25 to 29"   "Age 30 to 34"  
 [5] "Age 35 to 39"   "Age 40 to 44"   "Age 45 to 49"   "Age 50 to 54"  
 [9] "Age 55 to 59"   "Age 60 to 64"   "Age 65 to 69"   "Age 70 to 74"  
[13] "Age 75 or over"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">attr</span>(frs_benunit2122_short<span class="sc">$</span>FAMTYPBU,<span class="st">"label"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Family Type</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">attr</span>(frs_benunit2122_short<span class="sc">$</span>FAMTYPBU,<span class="st">"labels"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Any other category"      "Pensioner couple"       
[3] "Pensioner single"        "Couple with children"   
[5] "Couple without children" "Lone parent"            
[7] "Single without children"</code></pre>
</div>
</div>
<p><strong>Questions</strong></p>
<p>3. What do the variables measure and how?</p>
</section>
<section id="merging-data-sets" class="level2">
<h2 class="anchored" data-anchor-id="merging-data-sets">Merging data sets</h2>
<p>Why do we merge data? Merging datasets allows us to combine information from different sources to enhance the depth of our analysis. This is particularly relevant when dealing with survey data that captures different dimensions of information at multiple levels, such as individual and benefit unit levels.</p>
<p>By merging data that captures information at different levels we can examine how individual characteristics interact with benefit-unit-level variables to influence outcomes of interest. In this we might want to examine the relationship between individual happiness and family type. This requires assigning the benefit unit level variable to every individuals within that unit, before we can analyse it further.</p>
<p>How do we merge data? In order to effectively merge datasets you need to use common identifiers - unique keys present across all datasets involved in the merge. In this case, the FRS documentation provides us with the necessary information: what are the available identifiers and how to use them depending which datasets we want to merge.</p>
<p>In our case the SERNUM and BENUNIT variables are needed to merge the two datasets. Sernum represents the unique serial number of the household, and Benunit represents the identifier for the benefit unit (family) in the household.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#specify which datasets to merge and which columns to use for merging</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(frs_adult2122_short, frs_benunit2122_short, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"SERNUM"</span>, <span class="st">"BENUNIT"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Questions</strong></p>
<p>4. How many variables do we have in the new merge_data?</p>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing values</h2>
<p>Let’s now examine the frequency of our wellbeing variables.</p>
<p>We will temporarily convert the variables into factors using `as_factor()` and `mutate()` for a more meaningful output.</p>
<p>Review the frequency tables, examining the missing values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#the code below displays the results in a nice table  </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(HAPPYWB, ANXIOUS) <span class="sc">%&gt;%</span> <span class="co"># Select variables</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), as.factor)) <span class="sc">%&gt;%</span> <span class="co"># Convert all selected variables to factors</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Category"</span>) <span class="sc">%&gt;%</span> <span class="co"># Pivot data for easier counting</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Variable, Category) <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Count =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>) <span class="sc">%&gt;%</span> <span class="co"># Summarise counts</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Variable, <span class="at">values_from =</span> Count) <span class="sc">%&gt;%</span> <span class="co"># Pivot data to have variables as columns</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="st">"row"</span>) <span class="sc">%&gt;%</span> <span class="co"># Optionally, add totals row</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="co"># Display as a nice table </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: right;">ANXIOUS</th>
<th style="text-align: right;">HAPPYWB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">5890</td>
<td style="text-align: right;">185</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">1870</td>
<td style="text-align: right;">140</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">2606</td>
<td style="text-align: right;">299</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">1663</td>
<td style="text-align: right;">484</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: right;">1210</td>
<td style="text-align: right;">635</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: right;">1933</td>
<td style="text-align: right;">1633</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: right;">1114</td>
<td style="text-align: right;">1572</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: right;">1173</td>
<td style="text-align: right;">3153</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: right;">1083</td>
<td style="text-align: right;">4869</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: right;">429</td>
<td style="text-align: right;">3123</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: right;">376</td>
<td style="text-align: right;">3254</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">8161</td>
<td style="text-align: right;">8161</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">27508</td>
<td style="text-align: right;">27508</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Questions</strong></p>
<p>5. Why do you think there are so many system missing values (NA) for each of the well-being variables?</p>
<p>Note, you can use the documentation to check if needed (see [<a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9073#!/documentation">FRS documentation</a>]).</p>
<p>What does this mean when it comes to interpreting the percentages?</p>
<p><strong>Note:</strong> For ease of interpretation, we are converting the original numeric <code>FAMTYPBU</code> variable into labeled factors using&nbsp;<code>as_factor()</code>, so that they directly display the value labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>merged_data<span class="sc">$</span>FAMTYPBU <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(merged_data<span class="sc">$</span>FAMTYPBU)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>merged_data<span class="sc">$</span>IAGEGR4 <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(merged_data<span class="sc">$</span>IAGEGR4)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">#drop the "Any other category" level from the variable as it did not apply to anyone in the data</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>merged_data<span class="sc">$</span>FAMTYPBU <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(merged_data<span class="sc">$</span>FAMTYPBU)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="compare-unweighted-and-weighted-proportions" class="level2">
<h2 class="anchored" data-anchor-id="compare-unweighted-and-weighted-proportions">Compare unweighted and weighted proportions</h2>
<p>Let’s examine the unweighted responses first.</p>
<p>The `xtabs()` function can be used for categorical variables and the `summary()` function for continuous ones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(            <span class="do">### Round the results to one decimal</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span>            <span class="do">### Convert proportions to %  </span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(   <span class="do">### Compute proportions</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xtabs</span>(<span class="sc">~</span>FAMTYPBU,merged_data) <span class="do">### Compute frequencies</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FAMTYPBU
       Pensioner couple        Pensioner single    Couple with children 
                   20.8                    11.4                    21.2 
Couple without children             Lone parent Single without children 
                   23.7                     3.6                    19.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(            <span class="do">### Round the results to one decimal</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span>            <span class="do">### Convert proportions to %  </span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(   <span class="do">### Compute proportions</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xtabs</span>(<span class="sc">~</span>IAGEGR4,merged_data) <span class="do">### Compute frequencies</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IAGEGR4
  Age 16 to 19   Age 20 to 24   Age 25 to 29   Age 30 to 34   Age 35 to 39 
           1.2            3.7            5.5            7.0            7.6 
  Age 40 to 44   Age 45 to 49   Age 50 to 54   Age 55 to 59   Age 60 to 64 
           7.4            7.2            8.4            9.2            9.6 
  Age 65 to 69   Age 70 to 74 Age 75 or over 
           9.6            9.6           14.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unweigthed summary results</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(merged_data<span class="sc">$</span>HAPPYWB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   6.000   8.000   7.443   9.000  10.000    8161 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(merged_data<span class="sc">$</span>ANXIOUS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  0.000   0.000   2.000   2.985   5.000  10.000    8161 </code></pre>
</div>
</div>
<p>What is the (unweighted) percentage of individuals living in an couple without children? Would this be representative of the population?</p>
<p>Let’s compare with the weighted frequencies. We will use the <code>wtd.table()</code> from the <code>Hmisc</code> package. The weights are specified after the variable for which we request the frequencies in the command below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Raw output</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.table</span>(merged_data<span class="sc">$</span>FAMTYPBU,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$x
[1] "Pensioner couple"        "Pensioner single"       
[3] "Couple with children"    "Couple without children"
[5] "Lone parent"             "Single without children"

$sum.of.weights
[1]  7609640  4323246 11834547 13939344  1888755 12300368</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Converted into proportions            </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">wtd.table</span>(merged_data<span class="sc">$</span>FAMTYPBU,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4)<span class="sc">$</span>sum.of.weights),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.7  8.3 22.8 26.9  3.6 23.7</code></pre>
</div>
</div>
<p>Now what is the representative proportion of couples without children? 26.9, is this higher or lower than the unweighted proportion?</p>
<p>Let’s look at the relation between family type and happiness and compare the unweighted and weighted results?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unweighted</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="sc">%&gt;%</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(FAMTYPBU) <span class="sc">%&gt;%</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">happiness =</span> <span class="fu">round</span>(<span class="fu">mean</span>(HAPPYWB, <span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  FAMTYPBU                happiness
  &lt;fct&gt;                       &lt;dbl&gt;
1 Pensioner couple             7.96
2 Pensioner single             7.45
3 Couple with children         7.56
4 Couple without children      7.62
5 Lone parent                  6.91
6 Single without children      6.74</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weighted</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(FAMTYPBU) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">happiness =</span> <span class="fu">round</span>(<span class="fu">weighted.mean</span>(HAPPYWB,GROSS4, <span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  FAMTYPBU                happiness
  &lt;fct&gt;                       &lt;dbl&gt;
1 Pensioner couple             7.89
2 Pensioner single             7.41
3 Couple with children         7.53
4 Couple without children      7.54
5 Lone parent                  6.84
6 Single without children      6.8 </code></pre>
</div>
</div>
<p>Is there a difference between the results? Why do you thin there might or not be a difference?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#unweighted</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(IAGEGR4) <span class="sc">%&gt;%</span> </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">happiness =</span> <span class="fu">round</span>(<span class="fu">mean</span>(HAPPYWB, <span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   IAGEGR4        happiness
   &lt;fct&gt;              &lt;dbl&gt;
 1 Age 16 to 19        7.25
 2 Age 20 to 24        7.18
 3 Age 25 to 29        7.37
 4 Age 30 to 34        7.33
 5 Age 35 to 39        7.33
 6 Age 40 to 44        7.23
 7 Age 45 to 49        7.14
 8 Age 50 to 54        7.19
 9 Age 55 to 59        7.24
10 Age 60 to 64        7.41
11 Age 65 to 69        7.69
12 Age 70 to 74        7.8 
13 Age 75 or over      7.72</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#weighted</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>merged_data <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(IAGEGR4) <span class="sc">%&gt;%</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">happiness =</span> <span class="fu">round</span>(<span class="fu">weighted.mean</span>(HAPPYWB,GROSS4, <span class="at">na.rm=</span><span class="cn">TRUE</span>),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 2
   IAGEGR4        happiness
   &lt;fct&gt;              &lt;dbl&gt;
 1 Age 16 to 19        7.38
 2 Age 20 to 24        7.15
 3 Age 25 to 29        7.41
 4 Age 30 to 34        7.28
 5 Age 35 to 39        7.37
 6 Age 40 to 44        7.13
 7 Age 45 to 49        7.14
 8 Age 50 to 54        7.2 
 9 Age 55 to 59        7.23
10 Age 60 to 64        7.41
11 Age 65 to 69        7.58
12 Age 70 to 74        7.7 
13 Age 75 or over      7.71</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals"><strong>Confidence intervals</strong></h2>
<p>So far, we have just computed point estimates without worrying about their precision. We can compute confidence intervals to indicate the precision (uncertainty) of our estimates.</p>
<p><strong>Confidence intervals for numerical variables:</strong> Numerous R packages provide functionalities for calculating confidence intervals and standard errors for means. However, here we emphasise manual computation to gain a deeper understanding of the underlying processes.</p>
<p>Under the assumption of simple random sampling, a 95% confidence interval for the mean is calculated as the mean plus or minus 1.96 times the standard error of the mean. The standard error of the mean itself is the standard error of the mean (that is, the square root of its variance) divided by the square of the sample size. Since we have functions for computing weighted means and variance in R, we can compute:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>m.p.happy<span class="ot">&lt;-</span><span class="fu">wtd.mean</span>(merged_data<span class="sc">$</span>HAPPYWB,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>se.p.happy<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(merged_data<span class="sc">$</span>HAPPYWB,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>n.happy<span class="ot">&lt;-</span><span class="fu">sum</span>(merged_data<span class="sc">$</span>GROSS4[<span class="sc">!</span><span class="fu">is.na</span>(merged_data<span class="sc">$</span>HAPPYWB)])</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>ci.happy<span class="ot">&lt;-</span><span class="fu">c</span>(m.p.happy,m.p.happy<span class="fl">-1.96</span><span class="sc">*</span>(se.p.happy<span class="sc">/</span><span class="fu">sqrt</span>(n.happy)),</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>            m.p.happy<span class="fl">+1.96</span><span class="sc">*</span>(se.p.happy<span class="sc">/</span><span class="fu">sqrt</span>(n.happy)))</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>ci.happy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.374589 7.373868 7.375309</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>m.p.anxious<span class="ot">&lt;-</span><span class="fu">wtd.mean</span>(merged_data<span class="sc">$</span>ANXIOUS,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>se.p.anxious<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(merged_data<span class="sc">$</span>ANXIOUS,<span class="at">weights=</span>merged_data<span class="sc">$</span>GROSS4))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>n.anxious<span class="ot">&lt;-</span><span class="fu">sum</span>(merged_data<span class="sc">$</span>GROSS4[<span class="sc">!</span><span class="fu">is.na</span>(merged_data<span class="sc">$</span>ANXIOUS)])</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>ci.anxious<span class="ot">&lt;-</span><span class="fu">c</span>(m.p.anxious,m.p.anxious<span class="fl">-1.96</span><span class="sc">*</span>(se.p.anxious<span class="sc">/</span><span class="fu">sqrt</span>(n.anxious)),</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>              m.p.anxious<span class="fl">+1.96</span><span class="sc">*</span>(se.p.anxious<span class="sc">/</span><span class="fu">sqrt</span>(n.anxious)))</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>ci.anxious</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.059913 3.058935 3.060891</code></pre>
</div>
</div>
<p><strong>Questions</strong></p>
<ol start="6" type="1">
<li>How happy are people overall on a scale of 0 to 10?</li>
</ol>
<p><strong>Confidence intervals for categorical variables:</strong> The <code>DescTools</code> package provides <code>MultinomCI()</code> a handy function to compute confidence intervals for multinomial proportions.</p>
<p>We need to provide <code>MultinomCI()</code> with two parameters: the frequencies for which we would like a confidence interval, and the confidence interval we want.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the frequency table of the variable</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>category_freq <span class="ot">&lt;-</span> <span class="fu">table</span>(merged_data<span class="sc">$</span>FAMTYPBU)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the multinomial confidence intervals</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>ci_results <span class="ot">&lt;-</span><span class="fu">round</span>(((<span class="fu">MultinomCI</span>(category_freq, <span class="at">conf.level =</span> <span class="fl">0.95</span>))<span class="sc">*</span><span class="dv">100</span>),<span class="dv">1</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>ci_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         est lwr.ci upr.ci
Pensioner couple        20.8   20.2   21.4
Pensioner single        11.4   10.8   12.0
Couple with children    21.2   20.6   21.8
Couple without children 23.7   23.1   24.3
Lone parent              3.6    3.0    4.3
Single without children 19.3   18.7   19.9</code></pre>
</div>
</div>
</section>
<section id="answers" class="level2">
<h2 class="anchored" data-anchor-id="answers">Answers</h2>
<p>1. There are 27508 cases in the adult dataset and 18541 in the benunit dataset.</p>
<p>2. The total number of variables is 8 in the adult dataset and 3 in the benunit dataset..</p>
<p>3. For example, <code>HAPPYWB</code> records responses to the questions of “How happy did you feel yesterday?” on a scale of ‘Not at all happy’ to ‘Completely happy’. The <code>FAMTYPBU</code> from the benunit dataset provides the family type.</p>
<p>4. There are a total of 9 variables in the new merged data.</p>
<p>5. The wellbeing variables cannot be answered by proxy, so if the person is not present to answer then no answer is recorded.</p>
<ol start="6" type="1">
<li>People are relatively happy, with an average of 7.4 out of 10.</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="FRS_get_familiar_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>